### ISSUE TITLE
Raise custom parsing error on invalid TOML input

### ISSUE THREAD

**Issue by EpicWink** [bobfang1992/pytomlpp#11]
Currently, RuntimeErrors are raised. Not only are they not the most appropriate standard-library exception (usually ValueError would be used), but it's standard to raise a custom Exception for parsing errors (eg `pytomlpp.ParseError` or  `pytomlpp.DecodeError` or  `pytomlpp.TOMLDecodeError` etc)

**Comment by bobfang1992** [comment]
I agree. Was thinking the same.
