### ISSUE TITLE
conda build for different version of python. Also possibly different platforms (Mac/Windows)

### ISSUE THREAD

**Issue by bobfang1992** [bobfang1992/pytomlpp#12]
As pypi coming into shape this can be put on the map.

**Comment by h-vetinari** [comment]
Hey @bobfang1992, I was planning to ping you once the CI turned green, but now that I stumble over this issue, I thought I'd quickly mention: https://github.com/conda-forge/staged-recipes/pull/14903

**Comment by bobfang1992** [comment]
Hi thanks for the effort, what do I need to do here? @h-vetinari

**Comment by h-vetinari** [comment]
You don't need to do anything in particular, but you're welcome to join in debugging the packaging effort (and even become a co-maintainer of the "recipe" with me, if you want). :)

**Comment by bobfang1992** [comment]
Closing this as I am removing conda support. All install should be from pypi from now on.

**Comment by h-vetinari** [comment]
> Closing this as I am removing conda support.

You cannot "remove" conda support, it's already there:
```
conda install -c conda-forge pytomlpp
```
works, and will continue to keep working.

> All install should be from pypi from now on.

Please don't make this official advice, it's harmful.

**Comment by bobfang1992** [comment]
Hi sorry I was not clear on my message, we used to have an official conda pacakge but I removed it just now because it has a really old version. `conda-forge` may work but I am not the maintainer of that channel (I think conda-forge guys does it? I cannot remember submitting this pacakge to `conda-forge` myself. 

https://anaconda.org/dorafmon/dashboard/feed/

But anyway I think the recommended way is to use `pypi` now. I don't have much time to automate the `conda` release process. So I wanted to remove it.

**Comment by h-vetinari** [comment]
I'm one of the people maintaining the conda-forge package. The release process is automated, and 1.0.6 has just been released after I reviewed the changes.

I understand that you don't want to maintain your own channel (and you shouldn't, actually, for several reasons)

> I cannot remember submitting this pacakge to `conda-forge` myself.

I did, and I let you know further up in this thread. 🙃 
You're still welcome to join in overseeing how the packaging gets done on the "feedstock": https://github.com/conda-forge/pytomlpp-feedstock

**Comment by h-vetinari** [comment]
I also left a [comment](https://github.com/bobfang1992/pytomlpp/commit/2459b403ba053e4503f7e9b079ed3fbc4aa3cfc4#commitcomment-60424152) on https://github.com/bobfang1992/pytomlpp/commit/2459b403ba053e4503f7e9b079ed3fbc4aa3cfc4 that I can reiterate here: do you want to have a PR that adds instructions for installing from conda-forge? I strongly recommend that, but then, I'm biased 😅

**Comment by bobfang1992** [comment]
Hi,
Just in case you missed this reply:
>  do you want to have a PR that adds instructions for installing from conda-forge?
yeah sure I think that's reasonable, but I'd like to emphasis that I think I am not maintaining the conda-forge distribution, and I cannot remember who set it up or when it was set up. So please add one world or two if you submit a PR to say that we do not control that distribution. Thanks!



Best,
Bob

**Comment by h-vetinari** [comment]
> yeah sure I think that's reasonable, but I'd like to emphasis that I _think_ I am not maintaining the conda-forge channel, so please add one world or two if you submit a PR to say that we do not control that distribution. Thanks!

You are obviously not maintaining what you don't know about, but you are welcome to join, as I said. In the meantime, _I_ I'm maintaining the conda-forge [feedstock](https://github.com/conda-forge/pytomlpp-feedstock) where the recipe is hosted and the packages get built in CI.

Except in the most unusual circumstances, support in conda-forge for new versions will be very fast, on the order of a day or so after release. So I don't think people need to be concerned about the maintainership of conda-forge, because it's highly automated & fast, and also I'm explicitly trying to sync & collaborate with you. 🙃

**Comment by bobfang1992** [comment]
Cool thanks very much for the contribution! I was thinking about using condo to distribute as I myself was using conda but later our team moved to pypi entirely, and also contributor to this repo has all been using pypi so I kind of dropped my own effort to support a conda distribution but it is very good to see a condo-forge distro. I just simply did not know it exists so sorry for the confusion earlier. But it is very good to have it. Thanks a lot for your effort.


Best,
Bob
