### ISSUE TITLE
Load from and dump to streams

### ISSUE THREAD

**Issue by EpicWink** [bobfang1992/pytomlpp#17]
Have `pytomlpp.load` to parse TOML from a text stream, and `pytomlpp.dump` to serialise TOML to a text stream.

```python
import io, pytomlpp
stream = io.StringIO()
pytomlpp.dump({"spam": 42}, stream)
stream.seek(0)
print(pytomlpp.load(stream))
```

This will then match the functionality of the standard-library JSON module. This could be implemented in either Python or PyBind11, simply calling the existing `pytomlpp.loads` and `pytomlpp.dumps` for now. Further iterations I imagine could use C++ streams.

**Comment by bobfang1992** [comment]
I want to deal with all possible IO with pure python... I will think about this and see if I can implement it.

**Comment by bobfang1992** [comment]
Hey @EpicWink  do you know how to combine pure python code with the compiled module in one project? I imagine we need to change the `setup.[py|cfg]` a bit to do it but not sure how. Do you have any guidance on that?

**Comment by EpicWink** [comment]
Choose one:

1. For packages (directories of Python code, with __init__.py's) at the top level:
   * In the [options] section, specify `packages = find:`
   * In the [options.packages.find] section, specify `exclude = tests/` (etc)

2. For packages inside a subdirectory (eg "src/") (preferred):
   * In the [options] section, specify `packages = find:`, and specify

     ```
     package_dir =
       = src
     ```

   * In the [options.packages.find] section, specify `where = src` (etc)

3. For modules (individual Python files) at the top level
   * In the [options] section, specify `py_modules = <module name>`

4. For modules inside a subdirectory (preferred):
   * In the [options] section, specify `py_modules = <module name>`, and specify

     ```
     package_dir =
       = src
     ```

See [the documentation](https://setuptools.readthedocs.io/en/latest/setuptools.html#specifying-values)
