### ISSUE TITLE
Setup automated clang-format

### ISSUE THREAD

**Issue by bobfang1992** [bobfang1992/pytomlpp#30]
I would like to use clang-format so we can have a consistent style for the long run. This should be automated, or at least we should have a `.clang-format` file which specifies this style. Maybe add a `pre-commit` hook to this? I would love to see some suggestions on this.

**Comment by EpicWink** [comment]
Usually it's easiest to check in CI of the coffee matches the style, and fail the job of linting fails. Does clang-format have check-only functionality?

**Comment by bobfang1992** [comment]
Closed via df5845e8e0fcd117e2e43fc15680e74b2d130f3e
