### ISSUE TITLE
Booleans are dumped as integers

### ISSUE THREAD

**Issue by Yura52** [bobfang1992/pytomlpp#46]
Hi! Thank you for the nice wrapper! Just noticed that the type is not preserved for booleans, although it does not affect my workflow.

```python
>>> import pytomlpp as toml
>>> toml.dumps({'x': True})
'x = 1'
```

python==3.8.5
pytomlpp==0.3.4

**Comment by bobfang1992** [comment]
Thanks! I will take a look and get back to you.

**Comment by bobfang1992** [comment]
Hi this is fixed by my last commit and I am releasing a new version now. Please do let me know if you have further questions

**Comment by Yura52** [comment]
Thank you for the quick reply, I've updated the package and the problem is gone.
