### ISSUE TITLE
upload a source dist to PyPI

### ISSUE THREAD

**Issue by ioistired** [bobfang1992/pytomlpp#47]
Currently only pre-built wheels are uploaded on pypi, meaning unsupported platforms cannot install this package at all even if they can compile it. Please upload a source dist (setup.py sdist; twine upload dist/*) because as it stands I cannot install this on my ARM phone.

**Comment by ml-factobotics** [comment]
>I cannot install this on my ARM phone.

I got workaround with pipenv and istallation from gh, add package as 
`pytomlpp = {editable = true, ref = "master", git = "https://github.com/bobfang1992/pytomlpp.git"}`

**Comment by ioistired** [comment]
yes, I'm using `pytomlpp @ git+https://github.com/bobfang1992/pytoml.git@0.3.5`. the problem is, not everyone wants to or is able to compile the package from source. additionally, packages uploaded to pypi must only depend on other pypi packages, not git repositories.

**Comment by bobfang1992** [comment]
Hi thanks for the issue report, but I am not sure how to implement this... I was told I can only do binary dist. Any idea or documentation I can refer to?

**Comment by bobfang1992** [comment]
> I was told I can only do binary dist
I mean for pypi I can only do source distro... not sure what needed to be done for binary dist. Any documentation for me to get start on this?

**Comment by marzer** [comment]
@bobfang1992 this seems like it can automate the building and deploying of wheels for lots of platforms: https://github.com/pypa/cibuildwheel

Of note is the page on [Delivering to PyPI](https://cibuildwheel.readthedocs.io/en/stable/deliver-to-pypi/)

**Comment by bobfang1992** [comment]
> @bobfang1992 seems cibuildwheel can automate the building and deploying of wheels for lots of platforms (per [Delivering to PyPI](https://cibuildwheel.readthedocs.io/en/stable/deliver-to-pypi/))
> 
> is it just a matter of adding more platforms etc to the ci build matrix?

probably I think people don't need source dist, they need this project to be on more platforms. I can take a look at this sometime. Hopefully it is just about changing the configuration a bit.

**Comment by ioistired** [comment]
You should have both. You cannot account for every possible platform. And suppose a new python version is released, it would need to be rebuilt for the new version, and without a source dist, it'll be un-installable from pypi on that new version.

> I was told I can only do binary dist
Who told you this? It's just not true.

You can use [twine] to upload sdists like so:

```
$ ./setup.py sdist
$ twine upload dist/*
```

[twine]: https://twine.readthedocs.io/en/latest/

**Comment by ioistired** [comment]
Oh no, I didn't test to make sure that the sdist actually builds. It looks like it's not including the toml++ source in the package. Looking into it now

**Comment by ioistired** [comment]
I just pushed a895a2e54b01840b64d673155e2d1f98f978ec33 which attempts to fix this. It's copying .cpp and .hpp files correctly but not the .h files :sweat:

**Comment by marzer** [comment]
You don't need to copy any .cpp files from toml++, it's a header-only library. The only cpp files you'd be copying would be unit tests, heh.

**Comment by bobfang1992** [comment]
Let me know when you are ready for another PR @ioistired . Thannks!
