### ISSUE TITLE
Carriage return should fail parsing

### ISSUE THREAD

**Issue by pwwang** [bobfang1992/pytomlpp#68]
References:

- https://github.com/BurntSushi/toml-test/blob/v1.1.0/tests//invalid/control/comment-cr.toml
- https://github.com/BurntSushi/toml-test/blob/v1.1.0/tests//invalid/control/bare-cr.toml
- https://github.com/pwwang/toml-bench#testcomplianceinvalid

**Comment by marzer** [comment]
Hmm, this was fixed in toml++ 3.0.0, on which this library is based. Are you using a current version?

**Comment by pwwang** [comment]
You are right. The normalization happed when the file is read by `Path.read_text()` or `open(path, "r")`. 

`Path.read_bytes()` or `open(path, "rb")` should be the right way.

**Comment by marzer** [comment]
@pwwang nice project, btw. Interesting to see that using tomli's benchmark data shows pytomlpp as being faster than rtoml, but then using pytomlpp's own data it's the other way around. Looks like tomli's benchmark data tests a few more paths of the parser.

**Comment by pwwang** [comment]
Yep, it's funny. I noticed that, too. And it is actually sort of reproducible, even though the difference is negligible.
